#
# YAML Configuration File - app
#     Application Configuration File
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---
app:
  name: "Packfire Framework for PHP"
  version: "1.0"
  rootUrl: "http://mauris.sg/packfire"
  debug: false

security:
  disabled: false
  override: false
  identity: null
  
session:
  enabled: true
  name: packfire
  lifetime: 3600
  http: true
  secure: false

router:
  routes: "routing"
  enabled: true
  caching: true

database:
#  default: 
#    driver: mysql
#    host: localhost
#    dbname: packfire
#    user: root 
#    password: password
#  scaffold:
#    driver: mysql
#    host: localhost
#    dbname: packfire
#    user: root 
#    password: password

...