#
# YAML Configuration File - IoC
#     Inversion of Control - services definition
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---
#serviceName:
#  class: className
#  parameters:
#    - param1
#    - param2

exception.handler:
  class: Packfire\Exception\Handler\HttpHandler


security: # the security module is optional. The default security module does not identify or authenticate the users
  class: Packfire\Web\SecurityModule

# the messenger service
messenger:
  class: Packfire\Session\Messenger

#configure the logging functionality
logger:
  class: Packfire\Log\Logger
  parameters: 
    - 'pack/storage/log/default.log'

#set the session storage method
session.storage:
  class: Packfire\Session\Storage\SessionStorage
  parameters: []

# set the cache to use
cache:
  class: Packfire\Cache\FileCache

# this sets the debugger output method
debugger.output:
  class: Packfire\Debugger\Output\Firebug

...