#
# YAML Configuration File - app.local
#     Application Configuration File for Local Context
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---
app:
  name: "Packfire Framework for PHP"
  version: "1.0-sofia"
  rootUrl: "http://localhost/packfire-web"
  debug: true

security:
  disabled: true
  override: false
  identity: null

session:
  name: packfire
  lifetime: 3600
  http: true
  secure: false
  
routing:
  enabled: true
  caching: true

database:
#  default: 
#    driver: mysql
#    host: localhost
#    dbname: packfire
#    user: root 
#    password: password

...