#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

home:
  rewrite: "/"
  method: "get"
  actual: "Packfire\Web\Page\Controller"

getStarted:
  rewrite: "/get-started"
  method: "get"
  actual: "Packfire\Web\Page\GetStartedView"
  
screencasts:
  rewrite: "/screencasts"
  method: "get"
  actual: "Packfire\Web\Page\Controller:screencasts"
  
downloads:
  rewrite: "/downloads"
  method: get
  actual: "Packfire\Web\Page\Controller:downloads"
  
downloads.post:
  rewrite: "/downloads"
  method: post
  actual: "Packfire\Web\Page\Controller:downloads"
  params:
    download: int
  
downloadFile:
  rewrite: "/download/{id}"
  method: get
  actual: "Packfire\Web\Page\Controller:downloadFile"
  params:
    id: int
    
blogPosts:
   rewrite: "/blog"
   method: get
   actual: "Packfire\Web\Page\BlogView"
  
admin.home:
  rewrite: "/admin"
  method: get
  actual: "Admin"
  
admin.home.post:
  rewrite: "/admin"
  method: post
  actual: "Packfire\Web\Admin\Controller"
  params:
    title: any
    contentType: any
    content: any
  
adminSignIn:
  rewrite: "/admin/sign-in"
  method: get
  actual: "Packfire\Web\Admin\Controller:signIn"
  
adminSignIn.post:
  rewrite: "/admin/sign-in"
  method: post
  actual: "Packfire\Web\Admin\Controller:signIn"
  params:
    username: any
    password: any
  
admin.signOut:
  rewrite: "/admin/sign-out"
  method: get
  actual: "Packfire\Web\Admin\Controller:signOut"
  
admin.changePassword:
  rewrite: "/admin/password"
  method: get
  actual: "Packfire\Web\Admin\Controller:changePassword"
  
admin.changePassword.view:
  rewrite: "/admin/password"
  method: post
  actual: "Packfire\Web\Admin\Controller:changePassword"
  params:
    oldpassword: any
    newpassword: any
    confirmpassword: any
  
admin.manageUsers:
  rewrite: "/admin/users"
  method: [post, get]
  actual: "Packfire\Web\Admin\Controller:manageUsers"
  
admin.managePosts:
  rewrite: "/admin/posts"
  method: get
  actual: "Packfire\Web\Admin\Controller:managePosts"
  
admin.managePosts.post:
  rewrite: "/admin/posts"
  method: post
  actual: "Packfire\Web\Admin\Controller:managePosts"
  params:
    title: any
    contentType: any
    content: any

...