#
# YAML Configuration File - routing
#     Routing for the application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

home:
  rewrite: "/"
  method: "get"
  actual: "Home"

getStarted:
  rewrite: "/get-started"
  method: "get"
  actual: "view.home.HomeGetStartedView"
  
screencasts:
  rewrite: "/screencasts"
  method: "get"
  actual: "Home:screencasts"
  
downloads:
  rewrite: "/downloads"
  method: [get, post]
  actual: "Home:downloads"
  
downloadFile:
  rewrite: "/download/{id}"
  method: "get"
  actual: "Home:downloadFile"
  params:
    id: '[0-9]+'
  
admin.home:
  rewrite: "/admin"
  method: [post, get]
  actual: "Admin"
  
adminSignIn:
  rewrite: "/admin/sign-in"
  method: [post, get]
  actual: "Admin:signIn"
  
admin.signOut:
  rewrite: "/admin/sign-out"
  method: "get"
  actual: "Admin:signOut"
  
admin.changePassword:
  rewrite: "/admin/password"
  method: [post, get]
  actual: "Admin:changePassword"
  
admin.manageUsers:
  rewrite: "/admin/users"
  method: [post, get]
  actual: "Admin:manageUsers"
  
admin.managePosts:
  rewrite: "/admin/posts"
  method: [post, get]
  actual: "Admin:managePosts"
  
...